INSERT INTO `user`(`id`, `wx_id`, `name`, `sex`, `star`, `age`, `height`, `grade`, `school`, `dept`, `hobby`, `specialty`, `birth_place`, `address`, `update_time`, `is_del`, `phone_number`, `email`, `role`, `avatar`) VALUES (1, 'string', 'string', 'male', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2023-11-02 02:17:33', NULL, '110', 'string', 'string', 'string');
INSERT INTO `user`(`id`, `wx_id`, `name`, `sex`, `star`, `age`, `height`, `grade`, `school`, `dept`, `hobby`, `specialty`, `birth_place`, `address`, `update_time`, `is_del`, `phone_number`, `email`, `role`, `avatar`) VALUES (2, '1111', '2222', 'female', NULL, 111, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2222', NULL, NULL, NULL);
INSERT INTO `user`(`id`, `wx_id`, `name`, `sex`, `star`, `age`, `height`, `grade`, `school`, `dept`, `hobby`, `specialty`, `birth_place`, `address`, `update_time`, `is_del`, `phone_number`, `email`, `role`, `avatar`) VALUES (6, '110', '李雷', 'male', '白羊座', 25, 188, '本科', '大清学院', '财务', '唱;跳;rap', 'emo', '大清', '热河', '2023-11-04 01:55:24', 0, NULL, '110@gmail.com', 'string', NULL);
INSERT INTO `user`(`id`, `wx_id`, `name`, `sex`, `star`, `age`, `height`, `grade`, `school`, `dept`, `hobby`, `specialty`, `birth_place`, `address`, `update_time`, `is_del`, `phone_number`, `email`, `role`, `avatar`) VALUES (7, '111', '韩梅1', 'female', '白羊座', 25, 188, '本科', '大清学院', '财务', '唱;跳;rap', 'emo', '大清', '热河', '2023-11-04 01:55:24', 0, NULL, '110@gmail.com', 'string', NULL);
INSERT INTO `user`(`id`, `wx_id`, `name`, `sex`, `star`, `age`, `height`, `grade`, `school`, `dept`, `hobby`, `specialty`, `birth_place`, `address`, `update_time`, `is_del`, `phone_number`, `email`, `role`, `avatar`) VALUES (8, '122', '韩23', 'female', '白羊座', 25, 188, '本科', '大清学院', '财务', '唱;跳;rap', 'emo', '大清', '热河', '2023-11-04 01:55:24', 0, NULL, '110@gmail.com', 'string', NULL);
INSERT INTO `user`(`id`, `wx_id`, `name`, `sex`, `star`, `age`, `height`, `grade`, `school`, `dept`, `hobby`, `specialty`, `birth_place`, `address`, `update_time`, `is_del`, `phone_number`, `email`, `role`, `avatar`) VALUES (9, '123', '韩24', 'female', '白羊座', 25, 188, '本科', '大清学院', '财务', '唱;跳;rap', 'emo', '大清', '热河', '2023-11-04 01:55:24', 0, NULL, '110@gmail.com', 'string', NULL);
INSERT INTO `user`(`id`, `wx_id`, `name`, `sex`, `star`, `age`, `height`, `grade`, `school`, `dept`, `hobby`, `specialty`, `birth_place`, `address`, `update_time`, `is_del`, `phone_number`, `email`, `role`, `avatar`) VALUES (10, '1125', '李1125', 'male', '白羊座', 25, 188, '本科', '大清学院', '财务', '唱;跳;rap', 'emo', '大清', '热河', '2023-11-04 01:55:24', 0, NULL, '110@gmail.com', 'string', NULL);
INSERT INTO `user`(`id`, `wx_id`, `name`, `sex`, `star`, `age`, `height`, `grade`, `school`, `dept`, `hobby`, `specialty`, `birth_place`, `address`, `update_time`, `is_del`, `phone_number`, `email`, `role`, `avatar`) VALUES (11, '127', '李127', 'male', '白羊座', 25, 188, '本科', '大清学院', '财务', '唱;跳;rap', 'emo', '大清', '热河', '2023-11-04 01:55:24', 0, NULL, '110@gmail.com', 'string', NULL);
INSERT INTO `user`(`id`, `wx_id`, `name`, `sex`, `star`, `age`, `height`, `grade`, `school`, `dept`, `hobby`, `specialty`, `birth_place`, `address`, `update_time`, `is_del`, `phone_number`, `email`, `role`, `avatar`) VALUES (12, '119', '韩梅梅', 'female', '白羊座', 25, 188, '本科', '大清学院', '财务', '唱;跳;rap', 'emo', '大清', '热河', '2023-11-04 01:59:16', 0, NULL, '110@gmail.com', 'string', NULL);
